### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by farzadmf** [lucasepe/yo#1]
Hey, nice convenient tool :+1: 

However, I cannot install it using either `go install github.com/lucasepe/yo@latest` or `go get ...` with the following error:

```
go install github.com/lucasepe/yo@latest: github.com/lucasepe/yo@none updating to
	github.com/lucasepe/yo@v0.1.0: parsing go.mod:
	module declares its path as: github.com/lucasepe/ko
	        but was required as: github.com/lucasepe/yo
```

**Comment by lucasepe** [comment]
thank you very much! fixed now (I hope..)

**Comment by farzadmf** [comment]
Yes, it's fixed :slightly_smiling_face:
